from pathlib import Path
import csv
ROOT=Path(r"D:\Developer\After Effects Internals Guide")
p=ROOT/"datasets"/"ae-plugin-capability-frontier.csv"
with p.open(encoding="utf-8-sig",newline="") as f:
    reader=csv.DictReader(f); rows=list(reader); fields=reader.fieldnames
by={r["capability"]:r for r in rows}
new=[
{"capability":"Test whether a prior rendered frame is sufficient for a new request","host_scope":"After Effects","min_version":"RenderOptionsSuite4/RenderSuite5 lineage","public_route":"AEGP_IsRenderedFrameSufficient","internal_evidence":"request-sufficiency/cache-validity model","context_constraints":"compare complete Render Options objects; relation need not be symmetric","cache_dependency_safety":"host-defined semantic reuse relation","maturity":"S2","status":"supported-specialized","risk":"low","next_probe":"directed sufficiency matrix over ROI/downsample/world type/time/decode quality"},
{"capability":"Construct and extend host-compatible GUID/hash state","host_scope":"After Effects","min_version":"17.5.1-era frozen API","public_route":"AEGP_HashSuite1","internal_evidence":"MixHashGuid; BEE/TDB RenderGuid surfaces","context_constraints":"GUID-shaped domains are not proven mutually interchangeable","cache_dependency_safety":"safe primitive when used by API that documents the resulting GUID domain","maturity":"S2","status":"supported","risk":"low","next_probe":"compare HashSuite output relation with receipt/compute-cache/GUID-mix domains without assuming bit identity"},
{"capability":"Coordinate duplicate expensive computation across render threads","host_scope":"After Effects","min_version":"AE 2022+","public_route":"AEGP_ComputeCacheSuite1 / AEGP_ComputeIfNeededAndCheckout","internal_evidence":"in-flight cache-key state and checkout semantics","context_constraints":"caller chooses wait vs nonblocking pending result; key/data ownership rules apply","cache_dependency_safety":"host-managed single-flight cache per key","maturity":"S3","status":"supported-specialized","risk":"medium","next_probe":"contention benchmark varying compute cost, fan-out and wait policy"},
{"capability":"Ask whether an item changed over a time interval since an edit generation","host_scope":"After Effects","min_version":"Render Suite 2+ lineage","public_route":"AEGP_GetProjectTimestamp + AEGP_HasItemChangedSinceTimestamp","internal_evidence":"time-local validity model; modern BEE/TDB temporal identity surfaces","context_constraints":"historical contract; verify availability/version before relying on current host","cache_dependency_safety":"interval-local invalidation query","maturity":"S2","status":"supported-historical-lineage","risk":"medium","next_probe":"compare interval query with modern RenderGuid/trace under localized edits"},
]
new += [
{"capability":"Negotiate exact suite selector support at runtime","host_scope":"After Effects/PICA hosts","min_version":"all mapped suite eras","public_route":"AcquireSuite(name, selector) / ReleaseSuite","internal_evidence":"158-generation static matrix; runtime probe package","context_constraints":"unknown returned table must not be dereferenced without ABI layout","cache_dependency_safety":"not a render dependency surface","maturity":"S3","status":"supported-contract","risk":"low","next_probe":"EXP-PLUGIN-001 48 suite families x selectors 1..32"},
{"capability":"Render from command line in a fresh or reused AE host","host_scope":"After Effects","min_version":"aerender lineage-current","public_route":"aerender; optional -reuse","internal_evidence":"aerender help + process/module observations","context_constraints":"headless host may suppress UI/AEGP extension planes; fresh and reused hosts differ in warm state","cache_dependency_safety":"render semantics depend on target host/project; not equivalent to interactive UI state","maturity":"S2","status":"supported-headless","risk":"medium","next_probe":"fresh-vs-reuse module/plugin/cache inventory with identical fixture"},
{"capability":"Inspect runtime scripting members without hard-coding the documentation list","host_scope":"After Effects scripting","min_version":"current ExtendScript reflection surface","public_route":"ExtendScript object.reflect","internal_evidence":"EXP-SCRIPT-001 runtime reflection capture","context_constraints":"Reflection completeness is not itself a guarantee of callable/support semantics","cache_dependency_safety":"scripting observation only; project mutations still follow host invalidation","maturity":"S2","status":"supported-observation","risk":"low","next_probe":"compare runtime reflection against current scripting Guide per object"},
{"capability":"Preserve an object reference across callbacks without caching raw host handles","host_scope":"After Effects","min_version":"current contracts","public_route":"documented persistent IDs where available + reacquire short-lived AEGP handles","internal_evidence":"TDB stream-ID prototype vocabulary; short-lived AEGP reference contract","context_constraints":"identity namespace differs by object type and lifetime","cache_dependency_safety":"object identity is not render identity","maturity":"S2","status":"supported-pattern","risk":"medium","next_probe":"duplicate/copy-paste/undo/save-reload identity transition matrix"},
]
for r in new: by[r["capability"]]=r
out=list(by.values())
with p.open("w",encoding="utf-8",newline="") as f:
    w=csv.DictWriter(f,fieldnames=fields); w.writeheader(); w.writerows(out)
print("capabilities",len(out),"added_or_updated",len(new))
